# Generated by Django 5.1 on 2024-09-23 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_booking_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(default='C001', max_length=100, unique=True)),
                ('client_name', models.CharField(default='Unknown', max_length=100)),
                ('case_type', models.CharField(default='Civil', max_length=100)),
                ('filing_date', models.DateField(default='2023-10-01')),
                ('court_name', models.CharField(default='Unknown Court', max_length=100)),
                ('judge_assigned', models.CharField(blank=True, max_length=100, null=True)),
                ('opposing_counsel', models.CharField(blank=True, max_length=100, null=True)),
                ('case_status', models.CharField(choices=[('Open', 'Open'), ('Pending', 'Pending'), ('Closed', 'Closed')], default='Open', max_length=50)),
                ('case_description', models.TextField(default='No description provided')),
                ('evidence_list', models.TextField(blank=True, null=True)),
                ('witness_information', models.TextField(blank=True, null=True)),
                ('next_hearing_date', models.DateField(blank=True, null=True)),
                ('ADVOCATE', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.advocates')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
