# Generated by Django 5.1 on 2024-10-11 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_casenotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='casenotification',
            name='sender_advocate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications_advocate', to='myapp.advocates'),
        ),
    ]
